name: Daily Stock Notification

on:
  schedule:
    - cron: "* * * * *" # 09:00 Bulgaria time during winter, 09:00/10:00 depending DST
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 21

        - name: Make Gradle executable
          run: chmod +x ./gradlew

        - name: Run app
          env:
            TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          run: ./gradlew bootRun